//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap chest_b {
            get {
                object obj = ResourceManager.GetObject("chest_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_base {
            get {
                object obj = ResourceManager.GetObject("chest_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_c {
            get {
                object obj = ResourceManager.GetObject("chest_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_g {
            get {
                object obj = ResourceManager.GetObject("chest_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_gl {
            get {
                object obj = ResourceManager.GetObject("chest_gl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_s {
            get {
                object obj = ResourceManager.GetObject("chest_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_sl {
            get {
                object obj = ResourceManager.GetObject("chest_sl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest_t {
            get {
                object obj = ResourceManager.GetObject("chest_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_a {
            get {
                object obj = ResourceManager.GetObject("gem_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_base {
            get {
                object obj = ResourceManager.GetObject("gem_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_d {
            get {
                object obj = ResourceManager.GetObject("gem_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_e {
            get {
                object obj = ResourceManager.GetObject("gem_e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_r {
            get {
                object obj = ResourceManager.GetObject("gem_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_s {
            get {
                object obj = ResourceManager.GetObject("gem_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gem_t {
            get {
                object obj = ResourceManager.GetObject("gem_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;data&gt;
        ///  &lt;tiles&gt;
        ///    &lt;tile name=&quot;Dirt&quot; tileImage=&quot;0&quot; autoGenType=&quot;Building Block&quot; color=&quot;#AF8365&quot; /&gt;
        ///    &lt;tile name=&quot;Stone&quot; tileImage=&quot;1&quot; autoGenType=&quot;Ore Blend&quot; color=&quot;#808080&quot; /&gt;
        ///    &lt;tile name=&quot;Grass&quot; tileImage=&quot;2&quot; autoGenType=&quot;Grass Blend&quot; color=&quot;#1CD85E&quot; /&gt;
        ///    &lt;tile name=&quot;Plants&quot; tileImage=&quot;3&quot; color=&quot;Plants&quot;&gt;
        ///      &lt;subtile name=&quot;Mushroom&quot; frameX=&quot;9&quot; frameY=&quot;0&quot; /&gt;
        ///    &lt;/tile&gt;
        ///    &lt;tile name=&quot;Torch&quot; tileImage=&quot;4&quot; color=&quot;Light Source&quot; marker=&quot;Torch&quot; /&gt; &lt;! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap objects_altar {
            get {
                object obj = ResourceManager.GetObject("objects_altar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_base {
            get {
                object obj = ResourceManager.GetObject("objects_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_heart {
            get {
                object obj = ResourceManager.GetObject("objects_heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_hellforge {
            get {
                object obj = ResourceManager.GetObject("objects_hellforge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_shadow {
            get {
                object obj = ResourceManager.GetObject("objects_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_sign {
            get {
                object obj = ResourceManager.GetObject("objects_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_statue {
            get {
                object obj = ResourceManager.GetObject("objects_statue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_tombstone {
            get {
                object obj = ResourceManager.GetObject("objects_tombstone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_torch {
            get {
                object obj = ResourceManager.GetObject("objects_torch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_unknown {
            get {
                object obj = ResourceManager.GetObject("objects_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_a {
            get {
                object obj = ResourceManager.GetObject("ore_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_base {
            get {
                object obj = ResourceManager.GetObject("ore_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_c {
            get {
                object obj = ResourceManager.GetObject("ore_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_cob {
            get {
                object obj = ResourceManager.GetObject("ore_cob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_d {
            get {
                object obj = ResourceManager.GetObject("ore_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_g {
            get {
                object obj = ResourceManager.GetObject("ore_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_h {
            get {
                object obj = ResourceManager.GetObject("ore_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_i {
            get {
                object obj = ResourceManager.GetObject("ore_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_m {
            get {
                object obj = ResourceManager.GetObject("ore_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_myth {
            get {
                object obj = ResourceManager.GetObject("ore_myth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_o {
            get {
                object obj = ResourceManager.GetObject("ore_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ore_s {
            get {
                object obj = ResourceManager.GetObject("ore_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_arms {
            get {
                object obj = ResourceManager.GetObject("people_arms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_base {
            get {
                object obj = ResourceManager.GetObject("people_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_cloth {
            get {
                object obj = ResourceManager.GetObject("people_cloth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_demo {
            get {
                object obj = ResourceManager.GetObject("people_demo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_dryad {
            get {
                object obj = ResourceManager.GetObject("people_dryad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_guide {
            get {
                object obj = ResourceManager.GetObject("people_guide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_mech {
            get {
                object obj = ResourceManager.GetObject("people_mech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_merch {
            get {
                object obj = ResourceManager.GetObject("people_merch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_nurse {
            get {
                object obj = ResourceManager.GetObject("people_nurse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_oldman {
            get {
                object obj = ResourceManager.GetObject("people_oldman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_santa {
            get {
                object obj = ResourceManager.GetObject("people_santa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_spawn {
            get {
                object obj = ResourceManager.GetObject("people_spawn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_tinker {
            get {
                object obj = ResourceManager.GetObject("people_tinker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_wizard {
            get {
                object obj = ResourceManager.GetObject("people_wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
